//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts_IOU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relation
    {
        public int RelationID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RelationUserID { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
