//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts_IOU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> PurchaseID { get; set; }
        public int UserID { get; set; }
        public int RelationUserID { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
